import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Providers } from '../src/provider/heroui.provider';
import { AuthProvider } from '@/src/context/auth.context';

import { OpenAPI } from '@/src/api/generated';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  OpenAPI.BASE = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:9999';
  OpenAPI.WITH_CREDENTIALS = true;

  return (
    <html lang='en' className='dark' suppressHydrationWarning>
      <head>
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased `}>
        <AuthProvider>
          <Providers>{children}</Providers>
        </AuthProvider>
      </body>
    </html>
  );
}
